language: python
sudo: true
dist: xenial
python:
  - "3.6"
cache: pip
install:
  - pip install -q -r requirements.txt
  # try to capture output https://pypi.org/project/pytest-travis-fold/
  - pip install pytest-travis-fold
script:
  - pytest lstm_reward_function/tests
  - travis_wait 60 pytest -s action_state_generation/tests/test_online_train.py::test_online_train_dqn_gridworld
  - travis_wait 60 pytest -s action_state_generation/tests/test_online_train.py::test_online_train_lstm_gridworld
  - travis_wait 60 pytest -s action_state_generation/tests/test_online_train.py::test_online_train_lstm_rnn_gridworld
  - travis_wait 60 pytest -s action_state_generation/tests/test_online_train.py::test_online_train_dqn_rnn_gridworld
  - travis_wait 60 pytest -s action_state_generation/tests/test_online_train.py::test_online_train_cartpole
