language: python
sudo: true
dist: xenial
python:
  - "3.6"
cache: pip
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install -q -r requirements.txt
  # try to capture output https://pypi.org/project/pytest-travis-fold/
  - pip install pytest-travis-fold
script:
  - pytest lstm_reward_function/tests --cov=lstm_reward_function/
  - travis_wait 60 pytest action_state_generation/tests/test_online_train.py::test_online_train_dqn_gridworld
  - travis_wait 60 pytest action_state_generation/tests/test_online_train.py::test_online_train_lstm_gridworld
  - travis_wait 60 pytest action_state_generation/tests/test_online_train.py::test_online_train_lstm_rnn_gridworld
  - travis_wait 60 pytest action_state_generation/tests/test_online_train.py::test_online_train_dqn_rnn_gridworld
  - travis_wait 60 pytest action_state_generation/tests/test_online_train.py::test_online_train_dqn_cartpole
  - travis_wait 60 pytest action_state_generation/tests/test_online_train.py::test_online_train_dqn_lunar
after_success:
  - coveralls
